# Generated by Django 6.0.7 on 2026-08-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_resumematch'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumematch',
            name='experience_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resumematch',
            name='keyword_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resumematch',
            name='skills_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
