# Generated by Django 6.0.7 on 2026-08-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_resumematch_experience_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumematch',
            name='recommendations',
            field=models.JSONField(default=list),
        ),
    ]
